name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: unpack firebase file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$FIREBASE_SECRET" --output app/google-services.json app/google-services.json.gpg
      env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
    - name: test
      run: bash ./gradlew testDebugUnitTest --stacktrace